id: P008194
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W19963
  title: སུམ་རྟགས་ཀྱི་སྙིང་འགྲེལ་ལེགས་བཤད་འདྲེན་པའི་འཕོ་ཉ
  author: ''
  volumes:
    1b4ada1872554c2f997c9aa5e1781502:
      image_group_id: I5676
      title: ''
      volume_number: 1
      total_pages: 134
      base_file: v001.txt
