id: I0874BBBA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T16:16:54+00:00'
last_modified: '2022-06-09T05:09:16.042061+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W19963
  title: སུམ་རྟགས་ཀྱི་སྙིང་འགྲེལ་ལེགས་བཤད་འདྲེན་པའི་འཕོ་ཉ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    4C01:
      image_group_id: I5676
      title: ''
      total_pages: 134
      order: 1
      base_file: 4C01.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
